services:
  web:
    build: .
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y netcat &&
      while ! nc -z db 5432; do
        echo 'Waiting for database connection...';
        sleep 2;
      done;
      source activate awm_env &&
      python mapmyday/manage.py makemigrations &&
      python mapmyday/manage.py migrate &&
      python mapmyday/manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - ./mapmyday:/app/mapmyday
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: kartoza/postgis:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "20080:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - web
      - pgadmin

volumes:
  pgdata:
