# Generated by Django 5.1.3 on 2025-01-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_rename_visit_date_itinerary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
